---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ajodanwe/public_html/erwe/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
